notifications:
  email:
    on_success: always
    on_failure: always

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages: ["g++-8"]
    sources: ["ubuntu-toolchain-r-test"]

before_install:
  - CC='/usr/bin/gcc-8'
  - CXX='/usr/bin/g++-8'
  - echo ${CC} && ${CC} --version
  - echo ${CXX} && ${CXX} --version

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################

  # Make a dir for all
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  # Go back to ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

